platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: hello-go
outputs:
- name: coverage-results

run:
  path: sh
  args:
  - -exc
  - |
    ls -ltr
    go env
    pwd
    export GOPATH=$PWD/$name
    go env
    cd hello-go/src/cognizant.com/codeblue
    apt install glide
    pwd
    cd ..
    cd ..
    echo "START TESTING"
    go test cognizant.com/codeblue/test/
    echo "TEST DONE"
