platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: autopcftest
outputs:
- name: coverage-results

run:
  path: autopcftest/src/cognizant.com/codeblue/ci/tasks/unit-test.sh
