platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: autopcftes
outputs:
- name: coverage-results

run:
  path: autopcftes/src/cognizant.com/codeblue/ci/unit-test.sh
